version: "2"
services:
  app:
    build: .
    container_name: civitas-nyc_app
    environment:
      - VIRTUAL_HOST=${SUBDOMAIN}.${ROOT_HOST},www.${SUBDOMAIN}.${ROOT_HOST}
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=proxy
      - LETSENCRYPT_HOST=${SUBDOMAIN}.${ROOT_HOST},www.${SUBDOMAIN}.${ROOT_HOST}
      - LETSENCRYPT_EMAIL=admin@${ROOT_HOST}
      - HTTP_AUTH_LOGIN
      - HTTP_AUTH_PASSWORD
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external:
      name: proxy
