var aircraftBis = [
    {
        "manufacturer": "Fokker",
        "name": "100",
        "ICAO": "F100",
        "wingspan": null,
        "height": null,
        "ARC": "C-*",
        "IATA": "100",
        "wake": "M",
        "seats": 97
    },
    {
        "manufacturer": "BAe",
        "name": "146",
        "ICAO": "",
        "wingspan": null,
        "height": null,
        "ARC": "C-*",
        "IATA": "146",
        "wake": "M",
        "seats": 100
    },
    {
        "manufacturer": "BAe",
        "name": "146",
        "ICAO": "",
        "wingspan": null,
        "height": null,
        "ARC": "C-*",
        "IATA": "14F",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Airbus",
        "name": "A318/319/320/321",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "C-*",
        "IATA": "32S",
        "wake": "M",
        "seats": 164
    },
    {
        "manufacturer": "Airbus",
        "name": "A330",
        "ICAO": "A330",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "330",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Airbus",
        "name": "A330-200",
        "ICAO": "A332",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "332",
        "wake": "H",
        "seats": 250
    },
    {
        "manufacturer": "Airbus",
        "name": "A330-300",
        "ICAO": "A333",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "333",
        "wake": "H",
        "seats": 300
    },
    {
        "manufacturer": "Airbus",
        "name": "A340",
        "ICAO": "A340",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "340",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Airbus",
        "name": "A340-200",
        "ICAO": "A342",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "342",
        "wake": "H",
        "seats": 303
    },
    {
        "manufacturer": "Airbus",
        "name": "A340-300",
        "ICAO": "A343",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "343",
        "wake": "H",
        "seats": 221
    },
    {
        "manufacturer": "Airbus",
        "name": "A340-500",
        "ICAO": "A345",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "345",
        "wake": "H",
        "seats": 225
    },
    {
        "manufacturer": "Airbus",
        "name": "A340-600",
        "ICAO": "A346",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "346",
        "wake": "H",
        "seats": 380
    },
    {
        "manufacturer": "Airbus",
        "name": "A350",
        "ICAO": "A350",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "350",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Airbus",
        "name": "A350-1000",
        "ICAO": "A35K",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "351",
        "wake": "H",
        "seats": 366
    },
    {
        "manufacturer": "Airbus",
        "name": "A350-900",
        "ICAO": "A359",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "359",
        "wake": "H",
        "seats": 315
    },
    {
        "manufacturer": "Airbus",
        "name": "A380",
        "ICAO": "A380",
        "wingspan": null,
        "height": null,
        "ARC": "F-*",
        "IATA": "380",
        "wake": "H",
        "seats": 450
    },
    {
        "manufacturer": "Boeing",
        "name": "707/720",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "D-*",
        "IATA": "707",
        "wake": "H",
        "seats": 140
    },
    {
        "manufacturer": "Boeing",
        "name": "727",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "C-*",
        "IATA": "727",
        "wake": "M",
        "seats": 150
    },
    {
        "manufacturer": "Boeing",
        "name": "727",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "C-*",
        "IATA": "72F",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Boeing",
        "name": "727",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "C-*",
        "IATA": "72M",
        "wake": "M",
        "seats": 75
    },
    {
        "manufacturer": "Boeing",
        "name": "737",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "C-*",
        "IATA": "737",
        "wake": "M",
        "seats": 165
    },
    {
        "manufacturer": "Boeing",
        "name": "737",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "C-*",
        "IATA": "73F",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Boeing",
        "name": "747-100",
        "ICAO": "B741",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "741",
        "wake": "H",
        "seats": 400
    },
    {
        "manufacturer": "Boeing",
        "name": "747-300",
        "ICAO": "B743",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "743",
        "wake": "H",
        "seats": 400
    },
    {
        "manufacturer": "Boeing",
        "name": "747",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "747",
        "wake": "H",
        "seats": 420
    },
    {
        "manufacturer": "Boeing",
        "name": "747-300",
        "ICAO": "B743",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "74D",
        "wake": "H",
        "seats": 200
    },
    {
        "manufacturer": "Boeing",
        "name": "747",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "74F",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Boeing",
        "name": "747SP",
        "ICAO": "N74S",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "74L",
        "wake": "H",
        "seats": 400
    },
    {
        "manufacturer": "Boeing",
        "name": "747",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "74M",
        "wake": "H",
        "seats": 200
    },
    {
        "manufacturer": "Boeing",
        "name": "747-100",
        "ICAO": "B741",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "74T",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Boeing",
        "name": "747-300",
        "ICAO": "B743",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "74U",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Boeing",
        "name": "757",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "D-*",
        "IATA": "757",
        "wake": "H",
        "seats": 178
    },
    {
        "manufacturer": "Boeing",
        "name": "767-300",
        "ICAO": "B763",
        "wingspan": null,
        "height": null,
        "ARC": "D-*",
        "IATA": "763",
        "wake": "H",
        "seats": 229
    },
    {
        "manufacturer": "Boeing",
        "name": "767-400",
        "ICAO": "B764",
        "wingspan": null,
        "height": null,
        "ARC": "D-*",
        "IATA": "764",
        "wake": "H",
        "seats": 260
    },
    {
        "manufacturer": "Boeing",
        "name": "767",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "D-*",
        "IATA": "767",
        "wake": "H",
        "seats": 229
    },
    {
        "manufacturer": "Boeing",
        "name": "767",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "D-*",
        "IATA": "76F",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Boeing",
        "name": "767-300",
        "ICAO": "B763",
        "wingspan": null,
        "height": null,
        "ARC": "D-*",
        "IATA": "76Y",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Boeing",
        "name": "777",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "777",
        "wake": "H",
        "seats": 330
    },
    {
        "manufacturer": "Boeing",
        "name": "777-200LR",
        "ICAO": "B77L",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "77L",
        "wake": "H",
        "seats": 275
    },
    {
        "manufacturer": "Boeing",
        "name": "777-300ER",
        "ICAO": "B77W",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "77w",
        "wake": "H",
        "seats": 368
    },
    {
        "manufacturer": "Boeing",
        "name": "787-300",
        "ICAO": "B783",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "783",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Boeing",
        "name": "787-800",
        "ICAO": "B788",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "788",
        "wake": "H",
        "seats": 250
    },
    {
        "manufacturer": "Boeing",
        "name": "787-900",
        "ICAO": "B789",
        "wingspan": null,
        "height": null,
        "ARC": "E-*",
        "IATA": "789",
        "wake": "H",
        "seats": 300
    },
    {
        "manufacturer": "Antonov",
        "name": "AN-26",
        "ICAO": "AN26",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "A26",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Antonov",
        "name": "AN-28",
        "ICAO": "AN28",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "A28",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Antonov",
        "name": "AN-30",
        "ICAO": "AN30",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "A30",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Antonov",
        "name": "AN-32",
        "ICAO": "AN32",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "A32",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Gulfstream/Rockwell",
        "name": "(Aero)",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "ACD",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Ayres",
        "name": "LM-200",
        "ICAO": "LOAD",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "ALM",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Antonov",
        "name": "AN-24",
        "ICAO": "AN24",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "AN4",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Antonov",
        "name": "AN-26",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "AN6",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Eurocopter",
        "name": "(Aerospatiale)",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "APH",
        "wake": "n/a",
        "seats": null
    },
    {
        "manufacturer": "Avro",
        "name": "RJ100",
        "ICAO": "RJ1H",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "AR1",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Avro",
        "name": "RJ70",
        "ICAO": "RJ70",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "AR7",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Avro",
        "name": "RJ85",
        "ICAO": "RJ85",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "AR8",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Avro",
        "name": "RJ70",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "ARJ",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Avro",
        "name": "RJX85",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "ARX",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "British",
        "name": "Aerospace",
        "ICAO": "ATP",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "ATP",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Aerospatiale/Alenia",
        "name": "ATR",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "C-*",
        "IATA": "ATR",
        "wake": "M",
        "seats": 69
    },
    {
        "manufacturer": "Avro",
        "name": "RJX100",
        "ICAO": "RX1H",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "AX1",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Avro",
        "name": "RJX85",
        "ICAO": "RX85",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "AX8",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Beechcraft",
        "name": "twin",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "BE2",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Beechcraft",
        "name": "light",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "BEC",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Beechcraft",
        "name": "light",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "BEP",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Beechcraft",
        "name": "light",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "BET",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Bell",
        "name": "Helicopters",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "BH2",
        "wake": "n/a",
        "seats": null
    },
    {
        "manufacturer": "Pilatus",
        "name": "Britten-Norman",
        "ICAO": "BN2P",
        "wingspan": null,
        "height": null,
        "ARC": "A-*",
        "IATA": "BNI",
        "wake": "L",
        "seats": 9
    },
    {
        "manufacturer": "Bus",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "BUS",
        "wake": "n/a",
        "seats": null
    },
    {
        "manufacturer": "Cessna",
        "name": "light",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "CN1",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Cessna",
        "name": "light",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "CN2",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Cessna",
        "name": "light",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "CNA",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Cessna",
        "name": "light",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "CNC",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Cessna",
        "name": "Citation",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "CNJ",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Cessna",
        "name": "light",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "CNT",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Canadair",
        "name": "Regional",
        "ICAO": "CRJ1",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "CR1",
        "wake": "M",
        "seats": 50
    },
    {
        "manufacturer": "Canadair",
        "name": "Regional",
        "ICAO": "CRJ2",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "CR2",
        "wake": "M",
        "seats": 50
    },
    {
        "manufacturer": "Canadair",
        "name": "Regional",
        "ICAO": "CRJ7",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "CR7",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Canadair",
        "name": "Regional",
        "ICAO": "CRJ9",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "CR9",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Canadair",
        "name": "Regional",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "CRJ",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "CASA",
        "name": "/",
        "ICAO": "C212",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "CS2",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "CASA",
        "name": "/",
        "ICAO": "CN35",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "CS5",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Convair",
        "name": "CV-240",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "CVF",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Convair",
        "name": "CV-240",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "CVR",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Curtiss",
        "name": "C-46",
        "ICAO": "C46",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "CWC",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Fairchild",
        "name": "Dornier",
        "ICAO": "D228",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "D28",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Fairchild",
        "name": "Dornier",
        "ICAO": "D328",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "D38",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC-3",
        "ICAO": "DC3",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "D3F",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC-6A/B/C",
        "ICAO": "DC6",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "D6F",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC-8",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "D8F",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC-8-62",
        "ICAO": "DC86",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "D8L",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC-8",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "D8M",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC-8-72",
        "ICAO": "DC87",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "D8Q",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC-8-61",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "D8X",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC-8-71",
        "ICAO": "DC87",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "D8Y",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC-9-10",
        "ICAO": "DC91",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "D91",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC-9-20",
        "ICAO": "DC92",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "D92",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC-9-30",
        "ICAO": "DC93",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "D93",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC-9-40",
        "ICAO": "DC94",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "D94",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC-9-50",
        "ICAO": "DC95",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "D95",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC-9-30",
        "ICAO": "DC93",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "D9C",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC-9-40",
        "ICAO": "DC94",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "D9F",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC-9",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "D9F",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC-9-10",
        "ICAO": "DC91",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "D9X",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC-3",
        "ICAO": "DC3",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "DC3",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC6A/B",
        "ICAO": "DC6",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "DC6",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC-8",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "DC8",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Douglas",
        "name": "DC-9",
        "ICAO": "DC9",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "DC9",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Dassault",
        "name": "(Breguet",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "DF2",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Dassault",
        "name": "(Breguet",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "DF3",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Dassault",
        "name": "(Breguet",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "DFL",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "De",
        "name": "Havilland",
        "ICAO": "DH8A",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "DH1",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "De",
        "name": "Havilland",
        "ICAO": "DH8B",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "DH2",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "De",
        "name": "Havilland",
        "ICAO": "DH8D",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "DH4",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "De",
        "name": "Havilland",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "DH8",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "De",
        "name": "Havilland",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "DHB",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "De",
        "name": "Havilland",
        "ICAO": "DHC3",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "DHL",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "De",
        "name": "Havilland",
        "ICAO": "DHC3",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "DHO",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "De",
        "name": "Havilland",
        "ICAO": "DHC2",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "DHP",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "De",
        "name": "Havilland",
        "ICAO": "DHC3",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "DHS",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Embraer",
        "name": "170",
        "ICAO": "E170",
        "wingspan": null,
        "height": null,
        "ARC": "C-*",
        "IATA": "E70",
        "wake": "M",
        "seats": 70
    },
    {
        "manufacturer": "Embraer",
        "name": "190",
        "ICAO": "E190",
        "wingspan": null,
        "height": null,
        "ARC": "C-*",
        "IATA": "E90",
        "wake": "M",
        "seats": 90
    },
    {
        "manufacturer": "Embraer",
        "name": "EMB.120",
        "ICAO": "E120",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "EM2",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Embraer",
        "name": "170/190",
        "ICAO": "",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "EMJ",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Embraer",
        "name": "RJ135",
        "ICAO": "E135",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "ER3",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Embraer",
        "name": "RJ145",
        "ICAO": "E145",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "ER4",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Embraer",
        "name": "RJ140",
        "ICAO": "",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "ERD",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Embraer",
        "name": "RJ135",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "ERJ",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Fokker",
        "name": "F.28",
        "ICAO": "F28",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "F21",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Fokker",
        "name": "F.28",
        "ICAO": "F28",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "F22",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Fokker",
        "name": "F.28",
        "ICAO": "F28",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "F23",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Fokker",
        "name": "F.28",
        "ICAO": "F28",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "F24",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Fokker",
        "name": "F.27",
        "ICAO": "F27",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "F27",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Fokker",
        "name": "F.28",
        "ICAO": "F28",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "F28",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Fokker",
        "name": "50",
        "ICAO": "F50",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "F50",
        "wake": "M",
        "seats": 46
    },
    {
        "manufacturer": "Fokker",
        "name": "70",
        "ICAO": "F70",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "F70",
        "wake": "M",
        "seats": 79
    },
    {
        "manufacturer": "Fairchild",
        "name": "Dornier",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "FA7",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Fairchild",
        "name": "FH.227",
        "ICAO": "F27",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "FK7",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Fairchild",
        "name": "Dornier",
        "ICAO": "J328",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "FRJ",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Grumman",
        "name": "G.21",
        "ICAO": "G21",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "GRG",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Gulfstream",
        "name": "Aerospace",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "GRJ",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Grumman",
        "name": "G.73",
        "ICAO": "G73T",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "GRM",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Gulfstream",
        "name": "Aerospace",
        "ICAO": "G159",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "GRS",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "British",
        "name": "Aerospace",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "H25",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Helio",
        "name": "H-250",
        "ICAO": "COUC",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "HEC",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Hovercraft",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "HOV",
        "wake": "n/a",
        "seats": null
    },
    {
        "manufacturer": "Ilyushin",
        "name": "IL114",
        "ICAO": "I114",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "I14",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Ilyushin",
        "name": "IL96-300",
        "ICAO": "IL96",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "I93",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Ilyushin",
        "name": "IL96",
        "ICAO": "IL96",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "I9F",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Ilyushin",
        "name": "IL96M",
        "ICAO": "IL96",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "I9M",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Ilyushin",
        "name": "IL96-300",
        "ICAO": "IL96",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "I9X",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Ilyushin",
        "name": "IL96T",
        "ICAO": "IL96",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "I9Y",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Ilyushin",
        "name": "IL62",
        "ICAO": "IL62",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "IL6",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Ilyushin",
        "name": "IL96",
        "ICAO": "IL96",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "IL9",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Ilyushin",
        "name": "IL86",
        "ICAO": "IL86",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "ILW",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "British",
        "name": "Aerospace",
        "ICAO": "JS31",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "J31",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "British",
        "name": "Aerospace",
        "ICAO": "JS32",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "J32",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "British",
        "name": "Aerospace",
        "ICAO": "JS41",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "J41",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "British",
        "name": "Aerospace",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "JST",
        "wake": "L/M",
        "seats": null
    },
    {
        "manufacturer": "Junkers",
        "name": "Ju52/3M",
        "ICAO": "JU52",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "JU5",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Lockheed",
        "name": "L-1049",
        "ICAO": "CONI",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "L49",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "LET",
        "name": "410",
        "ICAO": "L410",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "L4T",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Launch",
        "name": "-",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "LCH",
        "wake": "n/a",
        "seats": null
    },
    {
        "manufacturer": "Limousine",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "LMO",
        "wake": "n/a",
        "seats": null
    },
    {
        "manufacturer": "Lockheed",
        "name": "L-188",
        "ICAO": "L188",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "LOE",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Lockheed",
        "name": "L-188",
        "ICAO": "L188",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "LOF",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Lockheed",
        "name": "L-188",
        "ICAO": "L188",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "LOM",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Gates",
        "name": "Learjet",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "LRJ",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "McDonnell",
        "name": "Douglas",
        "ICAO": "MD80",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "M80",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "McDonnell",
        "name": "Douglas",
        "ICAO": "MD81",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "M81",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "McDonnell",
        "name": "Douglas",
        "ICAO": "MD82",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "M82",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "McDonnell",
        "name": "Douglas",
        "ICAO": "MD83",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "M83",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "McDonnell",
        "name": "Douglas",
        "ICAO": "MD87",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "M87",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "McDonnell",
        "name": "Douglas",
        "ICAO": "MD88",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "M88",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "McDonnell",
        "name": "Douglas",
        "ICAO": "MD90",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "M90",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Eurocopter",
        "name": "(MBB)",
        "ICAO": "B105",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "MBH",
        "wake": "n/a",
        "seats": null
    },
    {
        "manufacturer": "MD",
        "name": "Helicopters",
        "ICAO": "EXPL",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "MD9",
        "wake": "n/a",
        "seats": null
    },
    {
        "manufacturer": "MIL",
        "name": "Mi-8",
        "ICAO": "MI8",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "MIH",
        "wake": "n/a",
        "seats": null
    },
    {
        "manufacturer": "Eurocopter",
        "name": "(Aerospatiale)",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "NDE",
        "wake": "n/a",
        "seats": null
    },
    {
        "manufacturer": "Eurocopter",
        "name": "(Aerospatiale)",
        "ICAO": "S65C",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "NDH",
        "wake": "n/a",
        "seats": null
    },
    {
        "manufacturer": "Piper",
        "name": "light",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "PA1",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Piper",
        "name": "light",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "PA2",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Piper",
        "name": "light",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "PAG",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Piper",
        "name": "light",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "PAT",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Pilatus",
        "name": "PC-12",
        "ICAO": "PC12",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "PL2",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Pilatus",
        "name": "PC-6",
        "ICAO": "PC6T",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "PL6",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Partenavia",
        "name": "P.68",
        "ICAO": "P68",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "PN6",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Road",
        "name": "Feeder",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "RFS",
        "wake": "n/a",
        "seats": null
    },
    {
        "manufacturer": "Saab",
        "name": "2000",
        "ICAO": "SB20",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "S20",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Sikorsky",
        "name": "S-58T",
        "ICAO": "S58T",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "S58",
        "wake": "n/a",
        "seats": null
    },
    {
        "manufacturer": "Sikorsky",
        "name": "S-61",
        "ICAO": "S61",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "S61",
        "wake": "n/a",
        "seats": null
    },
    {
        "manufacturer": "Sikorsky",
        "name": "S-76",
        "ICAO": "S76",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "S76",
        "wake": "n/a",
        "seats": null
    },
    {
        "manufacturer": "Saab",
        "name": "SF340A/B",
        "ICAO": "SF34",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "SF3",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Shorts",
        "name": "SC-5",
        "ICAO": "BELF",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "SHB",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Shorts",
        "name": "SC-7",
        "ICAO": "SC7",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "SHS",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Aerospatiale/BAC",
        "name": "Concorde",
        "ICAO": "CONC",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "SSC",
        "wake": "H",
        "seats": null
    },
    {
        "manufacturer": "Fairchild",
        "name": "(Swearingen)",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "SWM",
        "wake": "L",
        "seats": null
    },
    {
        "manufacturer": "Tupolev",
        "name": "Tu-204",
        "ICAO": "T204",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "T20",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Train",
        "ICAO": "n/a",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "TRN",
        "wake": "n/a",
        "seats": null
    },
    {
        "manufacturer": "Tupolev",
        "name": "Tu134",
        "ICAO": "T134",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "TU3",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Tupolev",
        "name": "Tu154",
        "ICAO": "T154",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "TU5",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Vickers",
        "name": "Viscount",
        "ICAO": "VISC",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "VCV",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Yakovlev",
        "name": "Yak",
        "ICAO": "YK42",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "YK2",
        "wake": "M",
        "seats": 104
    },
    {
        "manufacturer": "Yakovlev",
        "name": "Yak",
        "ICAO": "YK40",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "YK4",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "Harbin",
        "name": "Yunshuji",
        "ICAO": "Y12",
        "wingspan": null,
        "height": null,
        "ARC": "B-*",
        "IATA": "YN2",
        "wake": "M",
        "seats": 17
    },
    {
        "manufacturer": "Xian",
        "name": "Yunshuji",
        "ICAO": "AN24",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "YN7",
        "wake": "M",
        "seats": null
    },
    {
        "manufacturer": "NAMC",
        "name": "YS-11",
        "ICAO": "YS11",
        "wingspan": null,
        "height": null,
        "ARC": "*-*",
        "IATA": "YS1",
        "wake": "M",
        "seats": null
    }
]