
var profile = {
	"AIRLINE" = {
		"1": Aeromexico,
		"2": air canada,
		"3": air china,
		"4": air france,
		"5": air new zealand,
		"6": airtran,
		"7": alaska,
		"8": american,
		"9": ana,
		"10": asiana,
		"11": british,
		"12": cathay,
		"13": china airlines,
		"14": china easten,
		"15": delta,
		"16": emirates,
		"17": eva,
		"18": forntier,
		"19": hawaii,
		"20": japan airlines,
		"21": jetblue,
		"22": klm,
		"23": korean air,
		"24": lan,
		"25": lufthansa,
		"27": philip,
		"27": sas,
		"28": sinagporee,
		"29": southewst,
		"30": sun country,
		"31": swiss,
		"32": taca,
		"33": united,
		"34": united,
		"35": us airways,
		"36": virgin america,
		"37": virgin alantic,
		"38": westjet,
		"39": aer lingus,
		"40": other,
		"41": etidad
	}
}