var passenger_profiles = [
  {
    "name": "all.business.domestic.departing",
    "count": 2737,
    "percentage": 23,
    "brfood": 73,
    "food": 51,
    "bags": 41,
    "brshop": 49,
    "shop": 18,
    "weighted": "FALSE",
    "color": "#211463"
  },
  {
    "name": "all.business.domestic.transfer",
    "count": 349,
    "percentage": 3,
    "brfood": 77,
    "food": 57,
    "bags": 25,
    "brshop": 50,
    "shop": 20,
    "weighted": "FALSE",
    "color": "#35277D"
  },
  {
    "name": "all.business.international.departing",
    "count": 412,
    "percentage": 3,
    "brfood": 71,
    "food": 49,
    "bags": 73,
    "brshop": 42,
    "shop": 9,
    "weighted": "FALSE",
    "color": "#685BA9"
  },
  {
    "name": "all.business.international.transfer",
    "count": 167,
    "percentage": 1,
    "brfood": 79,
    "food": 60,
    "bags": 23,
    "brshop": 43,
    "shop": 11,
    "weighted": "FALSE",
    "color": "#4B3D92"
  },
  {
    "name": "all.leisure.domestic.departing",
    "count": 2781,
    "percentage": 23,
    "brfood": 71,
    "food": 49,
    "bags": 66,
    "brshop": 50,
    "shop": 20,
    "weighted": "FALSE",
    "color": "#8F600D"
  },
  {
    "name": "all.leisure.domestic.transfer",
    "count": 586,
    "percentage": 5,
    "brfood": 77,
    "food": 57,
    "bags": 26,
    "brshop": 47,
    "shop": 16,
    "weighted": "FALSE",
    "color": "#B58126"
  },
  {
    "name": "all.leisure.international.departing",
    "count": 968,
    "percentage": 8,
    "brfood": 72,
    "food": 50,
    "bags": 87,
    "brshop": 42,
    "shop": 10,
    "weighted": "FALSE",
    "color": "#F5C673"
  },
  {
    "name": "all.leisure.international.transfer",
    "count": 340,
    "percentage": 3,
    "brfood": 77,
    "food": 58,
    "bags": 22,
    "brshop": 42,
    "shop": 9,
    "weighted": "FALSE",
    "color": "#D3A047"
  },
  {
    "name": "all.other.domestic.departing",
    "count": 2217,
    "percentage": 19,
    "brfood": 68,
    "food": 45,
    "bags": 55,
    "brshop": 49,
    "shop": 19,
    "weighted": "FALSE",
    "color": "#2D8677"
  },
  {
    "name": "all.other.domestic.transfer",
    "count": 476,
    "percentage": 4,
    "brfood": 72,
    "food": 51,
    "bags": 25,
    "brshop": 52,
    "shop": 22,
    "weighted": "FALSE",
    "color": "#085B4D"
  },
  {
    "name": "all.other.international.departing",
    "count": 532,
    "percentage": 4,
    "brfood": 67,
    "food": 44,
    "bags": 85,
    "brshop": 42,
    "shop": 9,
    "weighted": "FALSE",
    "color": "#187263"
  },
  {
    "name": "all.other.international.transfer",
    "count": 271,
    "percentage": 2,
    "brfood": 74,
    "food": 53,
    "bags": 30,
    "brshop": 42,
    "shop": 10,
    "weighted": "FALSE",
    "color": "#499B8D"
  },
  {
    "name": "t1.business.domestic.departing",
    "count": 1117,
    "percentage": 34,
    "brfood": 70,
    "food": 47,
    "bags": 42,
    "brshop": 47,
    "shop": 17,
    "weighted": "FALSE",
    "color": "#211463"
  },
  {
    "name": "t1.business.domestic.transfer",
    "count": 62,
    "percentage": 2,
    "brfood": 78,
    "food": 58,
    "bags": 39,
    "brshop": 42,
    "shop": 10,
    "weighted": "FALSE",
    "color": "#35277D"
  },
  {
    "name": "t1.business.international.departing",
    "count": 1,
    "percentage": 0,
    "brfood": 108,
    "food": 100,
    "bags": 0,
    "brshop": 35,
    "shop": 0,
    "weighted": "FALSE",
    "color": "#685BA9"
  },
  {
    "name": "t1.business.international.transfer",
    "count": 0,
    "percentage": 0,
    "brfood": 0,
    "food": "NaN",
    "bags": "NaN",
    "brshop": 0,
    "shop": "NaN",
    "weighted": "FALSE",
    "color": "#4B3D92"
  },
  {
    "name": "t1.leisure.domestic.departing",
    "count": 1043,
    "percentage": 32,
    "brfood": 69,
    "food": 46,
    "bags": 67,
    "brshop": 49,
    "shop": 19,
    "weighted": "FALSE",
    "color": "#8F600D"
  },
  {
    "name": "t1.leisure.domestic.transfer",
    "count": 71,
    "percentage": 2,
    "brfood": 76,
    "food": 56,
    "bags": 41,
    "brshop": 44,
    "shop": 11,
    "weighted": "FALSE",
    "color": "#B58126"
  },
  {
    "name": "t1.leisure.international.departing",
    "count": 29,
    "percentage": 1,
    "brfood": 86,
    "food": 69,
    "bags": 79,
    "brshop": 35,
    "shop": 0,
    "weighted": "FALSE",
    "color": "#F5C673"
  },
  {
    "name": "t1.leisure.international.transfer",
    "count": 8,
    "percentage": 0,
    "brfood": 54,
    "food": 25,
    "bags": 0,
    "brshop": 35,
    "shop": 0,
    "weighted": "FALSE",
    "color": "#D3A047"
  },
  {
    "name": "t1.other.domestic.departing",
    "count": 897,
    "percentage": 27,
    "brfood": 67,
    "food": 43,
    "bags": 55,
    "brshop": 48,
    "shop": 18,
    "weighted": "FALSE",
    "color": "#2D8677"
  },
  {
    "name": "t1.other.domestic.transfer",
    "count": 65,
    "percentage": 2,
    "brfood": 72,
    "food": 51,
    "bags": 28,
    "brshop": 41,
    "shop": 8,
    "weighted": "FALSE",
    "color": "#085B4D"
  },
  {
    "name": "t1.other.international.departing",
    "count": 4,
    "percentage": 0,
    "brfood": 90,
    "food": 75,
    "bags": 100,
    "brshop": 35,
    "shop": 0,
    "weighted": "FALSE",
    "color": "#187263"
  },
  {
    "name": "t1.other.international.transfer",
    "count": 0,
    "percentage": 0,
    "brfood": 0,
    "food": "NaN",
    "bags": "NaN",
    "brshop": 0,
    "shop": "NaN",
    "weighted": "FALSE",
    "color": "#499B8D"
  },
  {
    "name": "t2.business.domestic.departing",
    "count": 626,
    "percentage": 32,
    "brfood": 76,
    "food": 55,
    "bags": 42,
    "brshop": 49,
    "shop": 19,
    "weighted": "FALSE",
    "color": "#211463"
  },
  {
    "name": "t2.business.domestic.transfer",
    "count": 34,
    "percentage": 2,
    "brfood": 80,
    "food": 62,
    "bags": 38,
    "brshop": 57,
    "shop": 29,
    "weighted": "FALSE",
    "color": "#35277D"
  },
  {
    "name": "t2.business.international.departing",
    "count": 1,
    "percentage": 0,
    "brfood": 35,
    "food": 0,
    "bags": 100,
    "brshop": 35,
    "shop": 0,
    "weighted": "FALSE",
    "color": "#685BA9"
  },
  {
    "name": "t2.business.international.transfer",
    "count": 0,
    "percentage": 0,
    "brfood": 0,
    "food": "NaN",
    "bags": "NaN",
    "brshop": 0,
    "shop": "NaN",
    "weighted": "FALSE",
    "color": "#4B3D92"
  },
  {
    "name": "t2.leisure.domestic.departing",
    "count": 663,
    "percentage": 34,
    "brfood": 73,
    "food": 52,
    "bags": 58,
    "brshop": 49,
    "shop": 19,
    "weighted": "FALSE",
    "color": "#8F600D"
  },
  {
    "name": "t2.leisure.domestic.transfer",
    "count": 62,
    "percentage": 3,
    "brfood": 83,
    "food": 66,
    "bags": 32,
    "brshop": 49,
    "shop": 19,
    "weighted": "FALSE",
    "color": "#B58126"
  },
  {
    "name": "t2.leisure.international.departing",
    "count": 20,
    "percentage": 1,
    "brfood": 79,
    "food": 60,
    "bags": 95,
    "brshop": 35,
    "shop": 0,
    "weighted": "FALSE",
    "color": "#F5C673"
  },
  {
    "name": "t2.leisure.international.transfer",
    "count": 2,
    "percentage": 0,
    "brfood": 72,
    "food": 50,
    "bags": 50,
    "brshop": 35,
    "shop": 0,
    "weighted": "FALSE",
    "color": "#D3A047"
  },
  {
    "name": "t2.other.domestic.departing",
    "count": 494,
    "percentage": 25,
    "brfood": 69,
    "food": 47,
    "bags": 51,
    "brshop": 48,
    "shop": 18,
    "weighted": "FALSE",
    "color": "#2D8677"
  },
  {
    "name": "t2.other.domestic.transfer",
    "count": 46,
    "percentage": 2,
    "brfood": 69,
    "food": 46,
    "bags": 26,
    "brshop": 50,
    "shop": 20,
    "weighted": "FALSE",
    "color": "#085B4D"
  },
  {
    "name": "t2.other.international.departing",
    "count": 6,
    "percentage": 0,
    "brfood": 72,
    "food": 50,
    "bags": 67,
    "brshop": 35,
    "shop": 0,
    "weighted": "FALSE",
    "color": "#187263"
  },
  {
    "name": "t2.other.international.transfer",
    "count": 0,
    "percentage": 0,
    "brfood": 0,
    "food": "NaN",
    "bags": "NaN",
    "brshop": 0,
    "shop": "NaN",
    "weighted": "FALSE",
    "color": "#499B8D"
  },
  {
    "name": "t3.business.domestic.departing",
    "count": 546,
    "percentage": 25,
    "brfood": 73,
    "food": 52,
    "bags": 34,
    "brshop": 47,
    "shop": 16,
    "weighted": "FALSE",
    "color": "#211463"
  },
  {
    "name": "t3.business.domestic.transfer",
    "count": 206,
    "percentage": 9,
    "brfood": 76,
    "food": 56,
    "bags": 18,
    "brshop": 49,
    "shop": 19,
    "weighted": "FALSE",
    "color": "#35277D"
  },
  {
    "name": "t3.business.international.departing",
    "count": 15,
    "percentage": 1,
    "brfood": 84,
    "food": 67,
    "bags": 60,
    "brshop": 35,
    "shop": 0,
    "weighted": "FALSE",
    "color": "#685BA9"
  },
  {
    "name": "t3.business.international.transfer",
    "count": 6,
    "percentage": 0,
    "brfood": 84,
    "food": 67,
    "bags": 0,
    "brshop": 35,
    "shop": 0,
    "weighted": "FALSE",
    "color": "#4B3D92"
  },
  {
    "name": "t3.leisure.domestic.departing",
    "count": 385,
    "percentage": 17,
    "brfood": 74,
    "food": 53,
    "bags": 62,
    "brshop": 46,
    "shop": 15,
    "weighted": "FALSE",
    "color": "#8F600D"
  },
  {
    "name": "t3.leisure.domestic.transfer",
    "count": 359,
    "percentage": 16,
    "brfood": 75,
    "food": 55,
    "bags": 23,
    "brshop": 44,
    "shop": 12,
    "weighted": "FALSE",
    "color": "#B58126"
  },
  {
    "name": "t3.leisure.international.departing",
    "count": 36,
    "percentage": 2,
    "brfood": 86,
    "food": 69,
    "bags": 81,
    "brshop": 35,
    "shop": 0,
    "weighted": "FALSE",
    "color": "#F5C673"
  },
  {
    "name": "t3.leisure.international.transfer",
    "count": 42,
    "percentage": 2,
    "brfood": 87,
    "food": 71,
    "bags": 21,
    "brshop": 39,
    "shop": 5,
    "weighted": "FALSE",
    "color": "#D3A047"
  },
  {
    "name": "t3.other.domestic.departing",
    "count": 297,
    "percentage": 13,
    "brfood": 69,
    "food": 47,
    "bags": 45,
    "brshop": 47,
    "shop": 16,
    "weighted": "FALSE",
    "color": "#2D8677"
  },
  {
    "name": "t3.other.domestic.transfer",
    "count": 283,
    "percentage": 13,
    "brfood": 75,
    "food": 54,
    "bags": 22,
    "brshop": 52,
    "shop": 22,
    "weighted": "FALSE",
    "color": "#085B4D"
  },
  {
    "name": "t3.other.international.departing",
    "count": 25,
    "percentage": 1,
    "brfood": 67,
    "food": 44,
    "bags": 48,
    "brshop": 35,
    "shop": 0,
    "weighted": "FALSE",
    "color": "#187263"
  },
  {
    "name": "t3.other.international.transfer",
    "count": 13,
    "percentage": 1,
    "brfood": 86,
    "food": 69,
    "bags": 15,
    "brshop": 35,
    "shop": 0,
    "weighted": "FALSE",
    "color": "#499B8D"
  },
  {
    "name": "ti.business.domestic.departing",
    "count": 448,
    "percentage": 10,
    "brfood": 75,
    "food": 54,
    "bags": 46,
    "brshop": 54,
    "shop": 25,
    "weighted": "FALSE",
    "color": "#211463"
  },
  {
    "name": "ti.business.domestic.transfer",
    "count": 47,
    "percentage": 1,
    "brfood": 79,
    "food": 60,
    "bags": 26,
    "brshop": 59,
    "shop": 32,
    "weighted": "FALSE",
    "color": "#35277D"
  },
  {
    "name": "ti.business.international.departing",
    "count": 395,
    "percentage": 9,
    "brfood": 71,
    "food": 48,
    "bags": 73,
    "brshop": 42,
    "shop": 9,
    "weighted": "FALSE",
    "color": "#685BA9"
  },
  {
    "name": "ti.business.international.transfer",
    "count": 161,
    "percentage": 4,
    "brfood": 79,
    "food": 60,
    "bags": 24,
    "brshop": 43,
    "shop": 11,
    "weighted": "FALSE",
    "color": "#4B3D92"
  },
  {
    "name": "ti.leisure.domestic.departing",
    "count": 690,
    "percentage": 16,
    "brfood": 71,
    "food": 49,
    "bags": 72,
    "brshop": 55,
    "shop": 27,
    "weighted": "FALSE",
    "color": "#8F600D"
  },
  {
    "name": "ti.leisure.domestic.transfer",
    "count": 94,
    "percentage": 2,
    "brfood": 78,
    "food": 59,
    "bags": 23,
    "brshop": 59,
    "shop": 32,
    "weighted": "FALSE",
    "color": "#B58126"
  },
  {
    "name": "ti.leisure.international.departing",
    "count": 883,
    "percentage": 20,
    "brfood": 71,
    "food": 49,
    "bags": 87,
    "brshop": 43,
    "shop": 11,
    "weighted": "FALSE",
    "color": "#F5C673"
  },
  {
    "name": "ti.leisure.international.transfer",
    "count": 288,
    "percentage": 7,
    "brfood": 77,
    "food": 57,
    "bags": 22,
    "brshop": 43,
    "shop": 10,
    "weighted": "FALSE",
    "color": "#D3A047"
  },
  {
    "name": "ti.other.domestic.departing",
    "count": 529,
    "percentage": 12,
    "brfood": 68,
    "food": 46,
    "bags": 66,
    "brshop": 53,
    "shop": 24,
    "weighted": "FALSE",
    "color": "#2D8677"
  },
  {
    "name": "ti.other.domestic.transfer",
    "count": 82,
    "percentage": 2,
    "brfood": 66,
    "food": 41,
    "bags": 37,
    "brshop": 62,
    "shop": 37,
    "weighted": "FALSE",
    "color": "#085B4D"
  },
  {
    "name": "ti.other.international.departing",
    "count": 497,
    "percentage": 11,
    "brfood": 67,
    "food": 43,
    "bags": 87,
    "brshop": 43,
    "shop": 10,
    "weighted": "FALSE",
    "color": "#187263"
  },
  {
    "name": "ti.other.international.transfer",
    "count": 258,
    "percentage": 6,
    "brfood": 73,
    "food": 52,
    "bags": 31,
    "brshop": 43,
    "shop": 10,
    "weighted": "FALSE",
    "color": "#499B8D"
  }
]